SunsetTown_JuliasHouse_2F_MapScripts::
	.byte 0


SunsetTown_JuliasHouse_2F_EventScript_NES::
	msgbox SunsetTown_JuliasHouse_2F_EventScript_NES_Text_0, MSGBOX_SIGN
	end


SunsetTown_JuliasHouse_2F_EventScript_Notebook::
	msgbox SunsetTown_JuliasHouse_2F_EventScript_Notebook_Text_0, MSGBOX_SIGN
	end


SunsetTown_JuliasHouse_2F_EventScript_AlexsPC::
	msgbox SunsetTown_JuliasHouse_2F_EventScript_AlexsPC_Text_0, MSGBOX_SIGN
	end


SunsetTown_JuliasHouse_2F_EventScript_NES_Text_0:
	.string "It's a NES with a GameBoy Advance SP\n"
	.string "plugged in as a controller.$"

SunsetTown_JuliasHouse_2F_EventScript_Notebook_Text_0:
	.string "It's a notebook with drawings\n"
	.string "JULIA made of some POKéMON.$"

SunsetTown_JuliasHouse_2F_EventScript_AlexsPC_Text_0:
	.string "It's JULIA's PC…\p"
	.string "Better get going!$ $"
