Route405_MapScripts::
	.byte 0


Route405_EventScript_RunningTriathleteF::
	msgbox Route405_EventScript_RunningTriathleteF_Text_0, MSGBOX_NPC
	end


Route405_EventScript_SwimmerM::
	msgbox Route405_EventScript_SwimmerM_Text_0, MSGBOX_NPC
	end


Route405_EventScript_RunningTriathleteF_Text_0:
	.string "How I got here?\p"
	.string "Swimming of course, I can't fly…$"

Route405_EventScript_SwimmerM_Text_0:
	.string "Woah woah!\p"
	.string "Were you on that boat that\n"
	.string "zoomed by just now?!$"
