#ifndef GUARD_DEBUG_H
#define GUARD_DEBUG_H
#if DEBUG

void Debug_OpenDebugMenu(void);

#define DEBUG_MAIN_MENU_WIDTH 7
#define DEBUG_UTILITY_MENU_WIDTH 12

#define DEBUG_NUMBER_DISPLAY_WIDTH 7
#define DEBUG_NUMBER_DISPLAY_HEIGHT 4

#define DEBUG_NUMBER_DIGITS_FLAGS 4

// Main Menu
enum {
    DEBUG_MENU_ITEM_UTILITY,
    DEBUG_MENU_ITEM_CANCEL,
};

// Utility Menu
enum {
    DEBUG_MENU_ITEM_MANAGE_FLAGS,
    DEBUG_MENU_ITEM_HEAL_PARTY,
    DEBUG_MENU_ITEM_GIVE_RARE_CANDY,
    DEBUG_MENU_ITEM_RESET_MAP_FLAGS,
    DEBUG_MENU_ITEM_PREPARE_TRADES,
};

#endif
#endif // GUARD_DEBUG_H