NavireTown_House3_MapScripts::
	.byte 0


NavireTown_House3_EventScript_FatMan::
	msgbox NavireTown_House3_EventScript_FatMan_Text_0, MSGBOX_NPC
	end


NavireTown_House3_EventScript_Man::
	msgbox NavireTown_House3_EventScript_Man_Text_0, MSGBOX_NPC
	end


NavireTown_House3_EventScript_FatMan_Text_0:
	.string "Oomph, I'm so full.\n"
	.string "Maybe I should eat a bit less…$"

NavireTown_House3_EventScript_Man_Text_0:
	.string "Sometimes you can even feel\n"
	.string "the vibrations of the work done\l"
	.string "at the OUREA CAVES all the way here.$"
